kserver.port=8082

spring.application.name=order-service

# MySQL (Docker container name)
spring.datasource.url=jdbc:mysql://microservice-mysql:3306/orderdb
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Eureka (FIXED ✅)
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
