# SERVER
server.port=8082
spring.application.name=order-service

# DATABASE (Docker container name)
spring.datasource.url=jdbc:mysql://microservice-mysql:3306/testdb
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# EUREKA (Docker container name)
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true